name: Deploy to Firebase Hosting
on: push
jobs:
  hosting:
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - uses: actions/checkout@v1

      # Install Flutter command
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'

      # Deploy Firebase Hosting
      - name: Deploy Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_TOKEN }}'
          projectId: test-project-demandas
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

